# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='content',
            field=models.TextField(default=b'', max_length=20000),
        ),
    ]
